In [33]:
#Bowerbird null model (all males are guarders)

#Key:
#Note: Paramters contain underscores, while functions don't
#SB- Stay at bower
#FG- Foraging
#a=-1 denotes a staying at bower action on ticket
#a=-2 denotes a foraging action on ticket
#networkwriter- generates network where everybird is connected
#addtotimeline- adds tickets to timeline


import math
import random
import numpy as np





# makes a ticket
def ticketgenerator(t, o, a):
    ticket={
        'time': t,
        'owner': o,
        'action': a,
    }
    return ticket;

#writes the edges to a network of n birds where everyone is connected to everyone else 
def networkwriter(n):
    connect=[0]*n
    for i in range(0, n): 
        a=list(range(n)) #generating a list that goes from 0 to n-1
        a.remove(i) #individual removes themselves from the network
        connect[i]=a #corresponds to the list of people person i is linked to
    return connect; #returns a list of lists with all the connections in the network

# function for determining the next time based on our rate parameters
def nexttau(rateParameter):
    taus=-math.log(1.0 - random.random()) / rateParameter #math.log is in base e, and random.random picks a number from range 0.0 to 1.
    return taus #generates n-length list, starting at index 0

#adds new tickets to timeline -- Stefano, any more efficient suggestions for keeping timeline in order?
def addtotimeline(tic, timeline):
    if not timeline:
        return [tic]
    ind=len(timeline)-1
    end=0
    while (tic['time']<timeline[ind]['time'] and end==0): #moves backwards until it finds where to place the ticket based on the listed times
        ind=ind-1 
        if(ind<0):
            end=1
    ind=ind+1
    timeline.insert(ind, tic)
    

def SBtickethandler (SB_tic, timeline,SB_param, t_max):
    ow=SB_tic['owner'] 
    t=SB_tic['time']
    FG_time=nexttau(SB_param)+t #We use SB_param because the time represents when the bird leaves the bower
    FG_tic=ticketgenerator(FG_time,ow,-2) #-2 denotes foraging action
    addtotimeline(FG_tic,timeline)

def FGtickethandler (FG_tic, timeline,FG_param, t_max):
    ow=FG_tic['owner'] 
    t=FG_tic['time']
    SB_time=nexttau(FG_param)+t #We use FG_param because the time represents when the bird returns to the bower
    SB_tic=ticketgenerator(SB_time,ow,-1) #-1 denotes staying at bower
    addtotimeline(SB_tic,timeline)
    
#FOR FUTURE: Write a function that generates a probability network of n bowerbirds 

#for now, we write a simple example network with 4 bowers forming a square
nodes=4

#HOW TO REPRESENT INDIVIDUAL'S DIST FROM SELF? nan?
distances = np.array([[150.0]*nodes]*nodes) #(dist in m)initialize a nodes-by-nodes matrix (1st nrows, 2nd ncols)
for i in range(4):
    distances[i][i]=9999.0 #or math.inf but that makes the matrix disp ugly
for i in range(2):
    distances[i][i+2]=((2*(150**2)))**(1/2)
    distances[i+2][i]=((2*(150**2)))**(1/2)


bird_speed=12 #m/s
travel_times=np.array([[0.0]*nodes]*nodes)
for i in range(nodes):
    for j in range(nodes):
        travel_times[i][j]=distances[i][j]/12
print(travel_times) #right now the numbers on the diagonals aren't accurate, but we can't have the bird choosing to go to it's own node

#will write female preference based on cumulative exponential decay (lambda=100/99)
female_preferences=np.array([[0.0]*nodes]*nodes)






    


[[833.25        12.5         17.67766953  12.5       ]
 [ 12.5        833.25        12.5         17.67766953]
 [ 17.67766953  12.5        833.25        12.5       ]
 [ 12.5         17.67766953  12.5        833.25      ]]


833.25

[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]


150.0